- name: Provision EC2 instance
  hosts: localhost
  vars:
    image_id: "ami-016eb5d644c333ccb" 
    instance_type: "t2.micro" 
    key_name: "shh_key" 
    region: "us-east-1" 
    subnet_id: "subnet-08ef7b3e735fe4487" 
    vpc_subnet_id: "vpc-0d8933cd63859a454" 
    security_groups: 
      - "sg-0ac99e5a037c06194"
      - "sg-0856fb08db7b466d0"
  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        name: "web_server"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        security_groups: "{{ security_groups }}"
        count: 1
        wait: yes
        subnet_id: "{{ subnet_id }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        filters:
          instance-state-name: running
          "tag:Name": "My EC2 Instance"
      register: running_instances